### ISSUE TITLE
stringTokens issues

### ISSUE THREAD

**Issue by bbouldin** [chrisGerken/gramar#9]
stringTokens generates NPEs:

Example (in main.prod):
```

  <c:log severity="info">
  
  This is a test log message.
  
  <c:stringTokens string="a test string 1234" var="word">
      word: <c:get select="$word/@value"/>
  </c:stringTokens>
  
  </c:log>
```

NPE happens on this line 38 of StringTokensTag.java:
```
			Element element = context.getPrimaryModel().getOwnerDocument().createElement(var);
```
The value of: context.getPrimaryModel().getOwnerDocument() is null.

Log is:
```
set variable newline = 

set variable tab = 	
set variable root = <root >
set variable apiSet = <apiSet  name="set1" >
java.lang.NullPointerException
	at org.gramar.base.tag.StringTokensTag.mergeTo(StringTokensTag.java:38)
	at org.gramar.tag.TagHandler.processChildren(TagHandler.java:120)
	at org.gramar.tag.TagHandler.processChildren(TagHandler.java:130)
	at org.gramar.base.tag.LogTag.mergeTo(LogTag.java:21)
	at org.gramar.tag.TagDocument.mergeTo(TagDocument.java:46)
	at org.gramar.ast.Template.mergeTo(Template.java:26)
	at org.gramar.platform.GramarPlatform.apply(GramarPlatform.java:108)
	at org.gramar.platform.GramarPlatform.apply(GramarPlatform.java:100)
	at org.gramar.platform.GramarPlatform.apply(GramarPlatform.java:85)
	at org.gramar.Apply.apply(Apply.java:120)
	at simple.java.project.gramar.ApiSet.main(ApiSet.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
set variable arg = <arg  name="arg1"  nameAllCaps="ARG1"  type="type1" >
unset variable arg
unset variable arg
unset variable apiSet
unset variable apiSet
java.lang.NullPointerException
In templates/main.prod
	[68,1] : <c:log severity="info">
	[72,1] : <c:stringTokens string="a test string 1234" var="word">
e = java.lang.NullPointerException


This is a test log message.

set variable apiSet = <apiSet  name="set1"  projectProject="set1project" >
Apply complete with status 4.  Model accessed 67 times
set variable arg = <arg  name="arg1"  nameAllCaps="ARG1"  type="type1" >
unset variable arg
unset variable arg
unset variable apiSet
unset variable apiSet
created project set1project
created file set1project/.classpath
created file set1project/.project
created folder set1project/.settings
created file set1project/.settings/org.eclipse.jdt.core.prefs
created folder set1project/bin
created folder set1project/src
created folder set1project/src/com
created folder set1project/src/com/brad
created folder set1project/src/com/brad/test
created file set1project/src/com/brad/test/MyMainClass.java

Process finished with exit code 0

```

Changing line 38 to this seems to fix the issue:
````
			Element element = context.getPrimaryModel().createElement(var);
````

***Other Issues***
The "string" property is treated as a raw value and so XPath expressions nested in curly brackets are not resolved. Making this change to StringTokensTag.java line 24 appears to fix the problem:
````
			String string = getStringAttribute("string", context);
````

For example:
<c:stringTokens string="{$root/apiSet[1]/arg[1]/@simpleString}" var="word">
    simpleString word: <c:get select="$word/@value"/>
</c:stringTokens>

with input:
```
<root>
    <apiSet  name="set1">
        <arg  name="arg1"  type="type1" simpleString="a simple string to parse"  nameAllCaps="ARG1">
        </arg>
    </apiSet>
</root>
```

produces:

    simpleString word: a
    simpleString word: simple
    simpleString word: string
    simpleString word: to
    simpleString word: parse

***Final issue***
The 'delimiter' property is unused in StringTokensTag.java. Adding this at line 66 (just after 'processChildren(...)' fixes the issue:
```
if (i > 0) {
    stream.append(delim);
}
```

**Comment by chrisGerken** [comment]
pushed a fix out onto the update site on gramar.org - Chris

Chris Gerken, Principal
512.587.5261      www.gerkenip.com

**Comment by chrisGerken** [comment]
but now I see that there’s more than just the npe… I’ll get to that stuff, too… - Chris

Chris Gerken, Principal
512.587.5261      www.gerkenip.com

**Comment by chrisGerken** [comment]
I think it's all fixed in the most recent commit
